# Generated by Django 5.1.3 on 2025-01-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_phone_number_customer_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/'),
        ),
    ]
