# Generated by Django 5.1.4 on 2025-01-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_company_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
